In [2]:
import torch
import numpy as np

In [3]:
# 텐서 초기화, 자료형 유추
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print("x_data : {}".format(x_data))

x_data : tensor([[1, 2],
        [3, 4]])


In [5]:
# test
x_data @ x_data

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
np_array = np.array(data)
print("np_array : {}\n".format(np_array))

x_np = torch.from_numpy(np_array)
print("x_np : {}".format(x_np))

np_array : [[1 2]
 [3 4]]

x_np : tensor([[1, 2],
        [3, 4]])


In [ ]:
# 다른 텐서로부터, 생성
x_ones = torch.ones_like(x_data)
print("x_ones : {}\n".format(x_ones))

x_rand = torch.rand_like(x_data, dtype=torch.float)
print("x_rand : {}".format(x_rand))

x_ones : tensor([[1, 1],
        [1, 1]])

x_rand : tensor([[0.8036, 0.1095],
        [0.5698, 0.4523]])


In [ ]:
shape = (2,3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("rand_tensor : {}\n".format(rand_tensor))
print("ones_tensor : {}\n".format(ones_tensor))
print("zeros_tensor : {}\n".format(zeros_tensor))

rand_tensor : tensor([[0.7328, 0.1968, 0.5334],
        [0.7010, 0.3510, 0.9466]])

ones_tensor : tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros_tensor : tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [ ]:
# 텐서의 속성

tensor = torch.rand(3,4)

print(tensor)

print(f"Shape of tensor : {tensor.shape}")
print(f"dtype of tensor : {tensor.dtype}")
print(f"device of tensor : {tensor.device}")

tensor([[0.6888, 0.2910, 0.7019, 0.4268],
        [0.7875, 0.4439, 0.2777, 0.2127],
        [0.0787, 0.9296, 0.3918, 0.6381]])
Shape of tensor : torch.Size([3, 4])
dtype of tensor : torch.float32
device of tensor : cpu


In [ ]:
# 텐서의 연산

# GPU가 존재하면 텐서를 이동.
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [ ]:
tensor = torch.ones(4,4)
print("First row : ", tensor[0])
print("First column : ", tensor[:, 0])
print("Last column : ", tensor[..., -1])
tensor[:, 1] = 0
print(tensor)

First row :  tensor([1., 1., 1., 1.])
First column :  tensor([1., 1., 1., 1.])
Last column :  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
tensor_cat = torch.cat([tensor, tensor, tensor], dim=1)
print(tensor_cat)

tensor_stack = torch.stack([tensor, tensor, tensor], dim=1)
print(tensor_stack)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [ ]:
# 두 텐서간의 행렬 곱

tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
result = tensor @ tensor
print(result)
tensor_matmul = tensor.matmul(tensor)
print(tensor_matmul)
result @ result

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


tensor([[ 7560,  9288, 11016],
        [17118, 21033, 24948],
        [26676, 32778, 38880]])

In [ ]:
t1 = torch.arange(9, dtype=int).view(3,3)
t2 = torch.arange(9, dtype=int).view(3,3)
print(t1)
print(t2)
t1 @ t2

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [ ]:
print("tensor : {}".format(tensor))
print("tensor.sum() : {}   tensor.sum().item() : {}".format(tensor.sum(), tensor.sum().item()))

# _  끝에 붙이면 inplace
tensor.add_(5)

tensor : tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor.sum() : 45   tensor.sum().item() : 45


tensor([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [ ]:
# numpy, tensor 캐스팅

t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

# 넘파이가 텐서에서 파생됬을때, 카피가 아니라, 래퍼런스를 공유함.
t.add_(3)
print(t)
print(n)

n = np.arange(10)
print(t)
print(n)
print()

n1 = np.arange(10)
t1 = torch.tensor(n1)
print(n1)
print(t1)
n1 = np.arange(5)
print(n1)
print(t1)
t1.add_(10)
print(n1)
print(t1)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]
tensor([4., 4., 4., 4., 4.])
[0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
[0 1 2 3 4]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
[0 1 2 3 4]
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


In [ ]:
# 반대도 마찮가지
n = np.ones(5)
t = torch.from_numpy(n)
print(n)
print(n,"\n")

np.add(n, 5, out=n)
print(n)
print(t)

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.] 

[6. 6. 6. 6. 6.]
tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
