In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [8]:
model = keras.Sequential(
    [
     layers.Dense(2, activation="relu", name="layer1"),
     layers.Dense(3, activation="relu", name="layer2"),
     layers.Dense(4, name="layer3")
    ]
)

x = tf.ones((3, 3))
y = model(x)

print(y)

tf.Tensor(
[[ 0.02051844 -0.01776471  0.01610004 -0.02442667]
 [ 0.02051844 -0.01776471  0.01610004 -0.02442667]
 [ 0.02051844 -0.01776471  0.01610004 -0.02442667]], shape=(3, 4), dtype=float32)


In [13]:
layer1 = layers.Dense(2, activation="relu", name="layer1")
layer2 = layers.Dense(3, activation="relu", name="layer2")
layer3 = layers.Dense(4, name="layer3")

x = tf.ones((3,3))
y = layer3(layer2(layer1(x)))

print(y)

tf.Tensor(
[[-0.6267352  -0.4136179  -0.34797776  0.22370146]
 [-0.6267352  -0.4136179  -0.34797776  0.22370146]
 [-0.6267352  -0.4136179  -0.34797776  0.22370146]], shape=(3, 4), dtype=float32)


In [34]:
x = tf.ones((3,3))

model_2 = keras.Sequential()
model_2.add(layers.Dense(2, activation="relu"))
model_2.add(layers.Dense(3, activation="relu"))
model_2.add(layers.Dense(4))

y = model_2(x)

print(y)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [37]:
model_2.pop()
print(len(model_2.layers))

0


# 미리 입력 형상 지정하기

In [61]:
layer = layers.Dense(3)
layer.weights

[]

In [62]:
x = tf.ones((3, 3))
y = layer(x)
layer.weights

[<tf.Variable 'dense_41/kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[ 0.85730267, -0.67584634, -0.12763381],
        [-0.26700664, -0.5260515 , -0.3256185 ],
        [-0.11481643, -0.94663787, -0.83337617]], dtype=float32)>,
 <tf.Variable 'dense_41/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [77]:
model_3 = keras.Sequential(
    [
     layers.Dense(2, activation="relu"),
     layers.Dense(3, activation="relu"),
     layers.Dense(4)
    ]
)

x = tf.ones((3,3))
y = model_3(x)
print(model_3.weights)  # 6

[<tf.Variable 'dense_84/kernel:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.19895828, -0.82584465],
       [-0.47905952,  0.42989898],
       [ 0.03538525, -0.9009412 ]], dtype=float32)>, <tf.Variable 'dense_84/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>, <tf.Variable 'dense_85/kernel:0' shape=(2, 3) dtype=float32, numpy=
array([[-0.11959022, -0.01756454, -0.7423872 ],
       [-0.10363013,  0.10123515,  0.51669455]], dtype=float32)>, <tf.Variable 'dense_85/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>, <tf.Variable 'dense_86/kernel:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.18287504, -0.5741167 , -0.4328977 , -0.37038928],
       [ 0.13894701,  0.17571735, -0.00666195,  0.3163426 ],
       [-0.29282868,  0.89552295, -0.11851645, -0.20405197]],
      dtype=float32)>, <tf.Variable 'dense_86/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]


In [80]:
model_3.summary()

Model: "sequential_32"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_84 (Dense)             (3, 2)                    8         
_________________________________________________________________
dense_85 (Dense)             (3, 3)                    9         
_________________________________________________________________
dense_86 (Dense)             (3, 4)                    16        
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [85]:
model_4 = keras.Sequential()
model_4.add(keras.Input(shape=(4,)))
model_4.add(layers.Dense(2, activation="relu"))

model_4.summary()

Model: "sequential_37"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_91 (Dense)             (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


In [87]:
model_4.layers

In [95]:
model_5 = keras.Sequential()
model_5.add(layers.Dense(2, activation="relu", input_shape=(4, )))

model_5.summary()

Model: "sequential_44"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_111 (Dense)            (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


# 일반적인 디버깅 워크플로우 : add() + summary()

In [97]:
model_6 = keras.Sequential()

model_6.add(keras.Input(shape=(250, 250, 3)))
model_6.add(layers.Conv2D(32, 5, strides=2, activation="relu"))
model_6.add(layers.Conv2D(32, 5, activation="relu"))
model_6.add(layers.MaxPooling2D(3))

model_6.summary()

model_6.add(layers.Conv2D(32, 3, activation="relu"))
model_6.add(layers.Conv2D(32, 3, activation="relu"))
model_6.add(layers.MaxPooling2D(3))
model_6.add(layers.Conv2D(32, 3, activation="relu"))
model_6.add(layers.Conv2D(32, 3, activation="relu"))
model_6.add(layers.MaxPooling2D(2))
print()
model_6.summary()
model_6.add(layers.GlobalMaxPooling2D())
model_6.add(layers.Dense(10))
print()
model_6.summary()

Model: "sequential_46"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 119, 119, 32)      25632     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 39, 39, 32)        0         
Total params: 28,064
Trainable params: 28,064
Non-trainable params: 0
_________________________________________________________________

Model: "sequential_46"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 119, 119, 32)      25632     
_________________________

# Sequential 모델을 사용한 특성 추출

In [121]:
initial_model = keras.Sequential(
    [
     keras.Input(shape=(250, 250, 3)),
     layers.Conv2D(32, 5, strides=2, activation="relu"),
     layers.Conv2D(32, 3, activation="relu"),
     layers.Conv2D(32, 3, activation="relu")
    ]
)
feature_extractor = keras.Model(
    inputs = initial_model.inputs,
    outputs=[layer.output for layer in initial_model.layers]
)

feature_extractor.summary()

Model: "model_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_31 (InputLayer)        [(None, 250, 250, 3)]     0         
_________________________________________________________________
conv2d_78 (Conv2D)           (None, 123, 123, 32)      2432      
_________________________________________________________________
conv2d_79 (Conv2D)           (None, 121, 121, 32)      9248      
_________________________________________________________________
conv2d_80 (Conv2D)           (None, 119, 119, 32)      9248      
Total params: 20,928
Trainable params: 20,928
Non-trainable params: 0
_________________________________________________________________


In [133]:
initial_model = keras.Sequential(
    [
     keras.Input(shape=(250,250,3)),
     layers.Conv2D(32, 5, strides=2, activation="relu"),
     layers.Conv2D(32, 3, activation="relu", name="my_intermediate_layer"),
     layers.Conv2D(32, 3, activation="relu")
    ]
)
feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    outputs=initial_model.get_layer(name="my_intermediate_layer").output
)
feature_extractor.summary()

Model: "model_26"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_43 (InputLayer)        [(None, 250, 250, 3)]     0         
_________________________________________________________________
conv2d_107 (Conv2D)          (None, 123, 123, 32)      2432      
_________________________________________________________________
my_intermediate_layer (Conv2 (None, 121, 121, 32)      9248      
Total params: 11,680
Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________


# Sequential 모델을 통한 전이 학습

In [134]:
model = keras.Sequential([<br>    keras.Input(shape=(784))<br>    layers.Dense(32, activation='relu'),<br>    layers.Dense(32, activation='relu'),<br>    layers.Dense(32, activation='relu'),<br>    layers.Dense(10),<br>])<br> <br># Presumably you would want to first load pre-trained weights.<br>model.load_weights(...)<br> <br># Freeze all layers except the last one.<br>for layer in model.layers[:-1]:<br>  layer.trainable = False<br> <br># Recompile and train (this will only update the weights of the last layer).<br>model.compile(...)<br>model.fit(...)

SyntaxError: ignored