In [1]:
import tensorflow as tf

In [25]:
x = tf.ones((2,2))
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y,y)

dz_dx = t.gradient(z, x)
print(x)
print(y)
print(z)
print(dz_dx)
for i in [0, 1]:
    for j in [0, 1]:
        assert dz_dx[i][j].numpy() == 8.0

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(16.0, shape=(), dtype=float32)
tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [27]:
x = tf.ones((2,2))
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y,y)

dz_dy = t.gradient(z, y)
print(x)
print(y)
print(z)
print(dz_dy)
assert dz_dy.numpy() == 8.0

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(16.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)


In [42]:
x = tf.constant(2.0)
with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    y = x * x
    z = y * y
dz_dx = t.gradient(z, x)
dy_dx = t.gradient(y, x)
del t
print(x)
print(y)
print(z)
print("-----------")
print(dz_dx)
print(dy_dx)

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(16.0, shape=(), dtype=float32)
-----------
tf.Tensor(32.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)


In [77]:
def f(x, y):
    output = 1.0
    for i in range(y):
        if i > 1 and i < 5:
            output = tf.multiply(output,x)
    return output

def grad(x, y):
    with tf.GradientTape() as t: # 실제로 연산의 값이 기록되는 구문
        t.watch(x)
        out = f(x, y)
    result = t.gradient(out, x) # 역전파
    print("result : ",result)
    return result

x = tf.convert_to_tensor(2.0)
print("x : ", x)
assert grad(x, 6).numpy() == 12.0
assert grad(x, 5).numpy() == 12.0
assert grad(x, 4).numpy() == 4.0

x :  tf.Tensor(2.0, shape=(), dtype=float32)
result :  tf.Tensor(12.0, shape=(), dtype=float32)
result :  tf.Tensor(12.0, shape=(), dtype=float32)
result :  tf.Tensor(4.0, shape=(), dtype=float32)


In [61]:
# 여기서 보여주는건, gradient 연산 또한, 기록이 될 수 있다는 점이다.

x = tf.Variable(1.0)

with tf.GradientTape() as t: # 연산 기록1
    with tf.GradientTape() as t2: # 연산 기록2
        y = x * x * x
    dy_dx = t2.gradient(y, x)
d2y_dx2 = t.gradient(dy_dx, x)

assert dy_dx.numpy() == 3.0
assert d2y_dx2.numpy() == 6.0