In [1]:
import tensorflow as tf

In [3]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))

# 연산자 오버로딩(overloading) 또한 지원합니다.
print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [4]:
x = tf.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [5]:
import numpy as np

ndarray = np.ones([3, 3])

print("텐서플로 연산은 자동적으로 넘파이 배열을 텐서로 변환합니다.")
tensor = tf.multiply(ndarray, 42)
print(tensor)


print("그리고 넘파이 연산은 자동적으로 텐서를 넘파이 배열로 변환합니다.")
print(np.add(tensor, 1))

print(".numpy() 메서드는 텐서를 넘파이 배열로 변환합니다.")
print(tensor.numpy())

텐서플로 연산은 자동적으로 넘파이 배열을 텐서로 변환합니다.
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
그리고 넘파이 연산은 자동적으로 텐서를 넘파이 배열로 변환합니다.
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
.numpy() 메서드는 텐서를 넘파이 배열로 변환합니다.
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


# GPU 가속

In [13]:
x = tf.random.uniform([3, 3])
print("GPU 가능 여부")
print(tf.test.is_gpu_available())
print()
print("텐서 GPU:0 할당 여부")
print(x.device.endswith("GPU:0"))

GPU 가능 여부
True

텐서 GPU:0 할당 여부
True


In [18]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(100):
        tf.matmul(x, x)
    result = time.time()-start
    print("100 loops: {:0.2f}ms\n".format(1000*result))

print("On CPU:")
with tf.device("CPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

if tf.test.is_gpu_available():
    print("On GPU:")
    with tf.device("GPU:0"):
        x = tf.random.uniform([1000, 1000])
        assert x.device.endswith("GPU:0")
        time_matmul(x)

On CPU:
100 loops: 2334.48ms

On GPU:
100 loops: 4.31ms



# 데이터셋

In [26]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, "w") as f:
    f.write("""Line 1
    Line 2
    Line 3
    """)
ds_file = tf.data.TextLineDataset(filename)

In [29]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.batch(2)

In [32]:
print("ds_tensors 요소")
for crnt in ds_tensors:
    print(crnt)
print()
print("\nds_file 요소")
for crnt in ds_file:
    print(x) 

ds_tensors 요소
tf.Tensor(
[[ 16  81]
 [256   1]], shape=(2, 2), dtype=int32)
tf.Tensor([[1296  625]], shape=(1, 2), dtype=int32)


ds_file 요소
tf.Tensor(
[[0.67559516 0.01601624 0.45243704 ... 0.64059603 0.94177866 0.76010597]
 [0.14391553 0.51484835 0.48600233 ... 0.38983738 0.4363948  0.39404547]
 [0.59548616 0.05927169 0.52347565 ... 0.1617614  0.989462   0.30452538]
 ...
 [0.68525875 0.30642188 0.8505324  ... 0.33941233 0.56782365 0.5403322 ]
 [0.48243654 0.00591505 0.32494724 ... 0.9253949  0.10197616 0.5338905 ]
 [0.4151945  0.5581316  0.29921818 ... 0.04627573 0.31047046 0.7799555 ]], shape=(1000, 1000), dtype=float32)
