In [2]:
import tensorflow as tf

In [7]:
leyer = tf.keras.layers.Dense(100)
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [8]:
layer(tf.ones([10, 5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[-1.2001914 ,  0.08795327,  0.28136563,  1.2310116 ,  1.0082242 ,
        -0.2803675 ,  0.38997254, -0.07741651,  0.98489964,  0.16209316],
       [-1.2001914 ,  0.08795327,  0.28136563,  1.2310116 ,  1.0082242 ,
        -0.2803675 ,  0.38997254, -0.07741651,  0.98489964,  0.16209316],
       [-1.2001914 ,  0.08795327,  0.28136563,  1.2310116 ,  1.0082242 ,
        -0.2803675 ,  0.38997254, -0.07741651,  0.98489964,  0.16209316],
       [-1.2001914 ,  0.08795327,  0.28136563,  1.2310116 ,  1.0082242 ,
        -0.2803675 ,  0.38997254, -0.07741651,  0.98489964,  0.16209316],
       [-1.2001914 ,  0.08795327,  0.28136563,  1.2310116 ,  1.0082242 ,
        -0.2803675 ,  0.38997254, -0.07741651,  0.98489964,  0.16209316],
       [-1.2001914 ,  0.08795327,  0.28136563,  1.2310116 ,  1.0082242 ,
        -0.2803675 ,  0.38997254, -0.07741651,  0.98489964,  0.16209316],
       [-1.2001914 ,  0.08795327,  0.28136563,  1.2310116 ,  1.00822

In [ ]:
layer.variables

[<tf.Variable 'dense_6/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.29701814, -0.6142936 , -0.05931199, -0.23063743,  0.1544711 ,
         -0.4045145 ,  0.47487408, -0.34199598, -0.03320271,  0.09699905],
        [-0.05518204, -0.27381048,  0.62157875, -0.24007142, -0.37124106,
          0.5643452 ,  0.4337582 ,  0.49670488,  0.56895643,  0.01558346],
        [ 0.50821894, -0.05470163, -0.60145235,  0.00511795, -0.54109055,
          0.57774955, -0.15183365,  0.01805717, -0.35833955,  0.40644985],
        [-0.36472443,  0.03815585,  0.21414441,  0.60040134,  0.5171893 ,
         -0.26579288,  0.06434035,  0.53574425,  0.4321862 , -0.49367508],
        [ 0.34730977,  0.20789087, -0.43162775, -0.44550216,  0.19133681,
         -0.05692351,  0.45707458, -0.1588977 ,  0.06755036,  0.25482506]],
       dtype=float32)>,
 <tf.Variable 'dense_6/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [ ]:
print(layer.kernel)
print()
print(layer.bias)

<tf.Variable 'dense_6/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.29701814, -0.6142936 , -0.05931199, -0.23063743,  0.1544711 ,
        -0.4045145 ,  0.47487408, -0.34199598, -0.03320271,  0.09699905],
       [-0.05518204, -0.27381048,  0.62157875, -0.24007142, -0.37124106,
         0.5643452 ,  0.4337582 ,  0.49670488,  0.56895643,  0.01558346],
       [ 0.50821894, -0.05470163, -0.60145235,  0.00511795, -0.54109055,
         0.57774955, -0.15183365,  0.01805717, -0.35833955,  0.40644985],
       [-0.36472443,  0.03815585,  0.21414441,  0.60040134,  0.5171893 ,
        -0.26579288,  0.06434035,  0.53574425,  0.4321862 , -0.49367508],
       [ 0.34730977,  0.20789087, -0.43162775, -0.44550216,  0.19133681,
        -0.05692351,  0.45707458, -0.1588977 ,  0.06755036,  0.25482506]],
      dtype=float32)>

<tf.Variable 'dense_6/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>


# 사용자 정의 층 구현

In [ ]:
class MyDenseLayer(tf.keras.layers.layers):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        print("init 호출")
        self.num_outputs = num_outputs

    def build(self, input_shape):
        print("build 호출")
        self.kernel = self.add_variable("kernel", shape=[int(input_shape[-1]),
                                                         self.num_outputs])
    def call(self, input):
        print("call 호출")
        return tf.matmul(input, self.kernel)

leyer2 = MyDenseLayer(20)

init 호출


In [ ]:
print(leyer2(tf.zeros([15, 5])))
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print(leyer2.trainable_variables)

build 호출
call 호출
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(15, 20), dtype=flo

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py:2191: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '


# 모델 층 구성
다른 층을 포함한 모델을 만들기 위해 사용하는 메인 클래스는 tf.keras.Model입니다. 다음은 tf.keras.Model을 상속(inheritance)하여 구현한 코드입니다.

In [ ]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name="")

        filter1, filter2, filter3 = filters
        
        leyer_group = tf.keras.layers

        self.conv2a = leyer_group.Conv2D(filter1, (1, 1))
        self.bn2a = leyer_group.BatchNormalization()

        self.conv2b = leyer_group.Conv2D(filter2, kernel_size)
        self.bn2b = leyer_group.BatchNormalization()

        self.conv2c = leyer_group.Conv2D(filter3, (1, 1))
        self.bn2c = leyer_group.BatchNormalization()

    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(input_tensor)
        x = tf.nn.relu(x)

        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv2c(x)
        x = self.bn2c(x, training=training)

        x += input_tensor
        return tf.nn.relu(x)

block = ResnetIdentityBlock(1, [1,2,3])
print(block(tf.zeros([1,2,3,3])))
print()
print([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)

['resnet_identity_block_5/conv2d_15/kernel:0', 'resnet_identity_block_5/conv2d_15/bias:0', 'resnet_identity_block_5/batch_normalization_15/gamma:0', 'resnet_identity_block_5/batch_normalization_15/beta:0', 'resnet_identity_block_5/conv2d_16/kernel:0', 'resnet_identity_block_5/conv2d_16/bias:0', 'resnet_identity_block_5/batch_normalization_16/gamma:0', 'resnet_identity_block_5/batch_normalization_16/beta:0', 'resnet_identity_block_5/conv2d_17/kernel:0', 'resnet_identity_block_5/conv2d_17/bias:0', 'resnet_identity_block_5/batch_normalization_17/gamma:0', 'resnet_identity_block_5/batch_normalization_17/beta:0']


In [ ]:
# 간단한 층 Sequential 사용

my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1,1), input_shape=(None,None,3)),
                              tf.keras.layers.BatchNormalization(),
                              tf.keras.layers.Conv2D(2, 1, padding="same"),
                              tf.keras.layers.BatchNormalization(),
                              tf.keras.layers.Conv2D(3, (1,1)),
                              tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1,2,3,3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>